
title: Oliver Griffiths Portfolio
email: oliver.griffiths@example.com
description: >-
  AI Software Engineering Portfolio and Learning Journey
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://OliG543.github.io" # the base hostname & protocol for your site

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - roadmap.md
  - blog.md
  - time_tracking.md
